### ISSUE TITLE
Add library to log control

### ISSUE THREAD

**Issue by dorianneto** [podcastcrawler/podcastcrawler#1]
Monolog it's a good option :)

**Comment by slax0rr** [comment]
Can you please provide a more specific description of what's desired? I can add monolog to your library, but what exactly do you want to log?

**Comment by dorianneto** [comment]
Hi @slax0rr, 

Firstly, thanks for interest on the project!

Actually my intention it's only store the possible errors occasioned from providers (Itunes for example).

During the development I saw that connection error from providers happens much more than normal and I consider that save the log for this looks good.

How do you see that?

**Comment by slax0rr** [comment]
@dorianneto I do not know what kind of errors are occuring from those providers, but I can add you the library, and you can fine-tune the logging later should you need to.
